# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    hide_cursor = false
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(240, 237, 230, 1)
    font_size = 108
    font_family = StretchPro
    position = 0, 150
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A · %d.%m.%Y")"
    color = rgba(207, 199, 188, 1)
    font_size = 18
    font_family = Suisse Int'l Mono
    position = 0, 40
    halign = center
    valign = center
}

# IDENTITY
label {
    monitor =
    text = $USER
    color = rgba(207, 199, 188, 1)
    font_size = 16
    font_family = Suisse Int'l Mono
    position = 0, -160
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 340, 52
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(230, 226, 219, 1)
    inner_color = rgba(20, 20, 20, 1)
    font_color = rgb(240, 237, 230)
    fade_on_empty = false
    font_family = Suisse Int'l Mono
    placeholder_text = <span foreground="#cfc7bc">UNLOCK</span>
    hide_input = false
    position = 0, -230
    halign = center
    valign = center
}

# ACTIVE KEYBOARD LAYOUT
label {
    monitor =
    text = $LAYOUT[en,ru]
    color = rgba(207, 199, 188, 1)
    font_size = 16
    font_family = Suisse Int'l Mono
    position = 198, -230
    halign = center
    valign = center
}
